window.tData = {
    isRegistr: false,
    isLogin: false,
    imageList: [{
        imgId: '0',
        author: 'Leo',
        isLike: false,
        authorAvatar: './images/user/userimg1.jpg',
        title: '别浪猥琐发育',
        src: './images/show1.jpg'
    }, {
        imgId: '1',
        author: 'Tiffany',
        isLike: false,
        authorAvatar: './images/user/userimg.jpg',
        title: '稳住我们能赢',
        src: './images/show2.jpg'
    }, {
        imgId: '2',
        author: '陈老师',
        isLike: false,
        authorAvatar: './images/user/edc.jpg',
        title: '上单不给就送',
        src: './images/show1.jpg'
    }, {
        imgId: '3',
        author: '马云',
        isLike: false,
        authorAvatar: './images/user/mayun.jpg',
        title: '不要想着单杀',
        src: './images/show2.jpg'
    }, {
        imgId: '4',
        author: 'Pony',
        isLike: false,
        authorAvatar: './images/user/mahuateng.jpg',
        title: '好好补兵',
        src: './images/show1.jpg'
    }],
    // diy1
    sizeList: [{
        id: 0,
        price: '￥10.00',
        text: 'S',
        model: '165/88A',
        shoulderWidth: 44,
        bust: 100,
        length: 66
    }, {
        id: 1,
        price: '￥10.00',
        text: 'M',
        model: '172/92A',
        shoulderWidth: 45,
        bust: 104,
        length: 68
    }, {
        id: 2,
        price: '￥10.00',
        text: 'L',
        model: '175/96A',
        shoulderWidth: 46,
        bust: 108,
        length: 70
    }, {
        id: 3,
        price: '￥10.00',
        text: 'XL',
        model: '180/100A',
        shoulderWidth: 48,
        bust: 112,
        length: 72
    }],
    // diy1
    typeList: [{
        id: 0,
        price: '￥233.00',
        text: '口袋短袖',
        imgSrc: './images/t-type/tshirt1.jpg'
    }, {
        id: 1,
        price: '￥233.00',
        text: '基本款短袖',
        imgSrc: './images/t-type/tshirt2.jpg'
    }, {
        id: 2,
        price: '￥233.00',
        text: '前短后长短袖',
        imgSrc: './images/t-type/tshirt3.jpg'
    }],
    // diy1
    colorList: [{
        id: 0,
        price: '￥15.00',
        text: '黑色',
        color: '#000000',
        imgSrc: './images/t-color/blackt.jpg'
    }, {
        id: 1,
        price: '￥15.00',
        text: '天蓝色',
        color: '#C4DDFC',
        imgSrc: './images/t-color/bluet.jpg'
    }, {
        id: 2,
        price: '￥15.00',
        text: '灰色',
        color: '#CBCBCB',
        imgSrc: './images/t-color/grayt.jpg'
    }, {
        id: 3,
        price: '￥15.00',
        text: '绿色',
        color: '#D1FDDC',
        imgSrc: './images/t-color/greent.jpg'
    }, {
        id: 4,
        price: '￥15.00',
        text: '骚粉色',
        color: '#FFD9C6',
        imgSrc: './images/t-color/orenget.jpg'
    }, {
        id: 5,
        price: '￥15.00',
        text: '粉红色',
        color: '#FDBACC',
        imgSrc: './images/t-color/pinkt.jpg'
    }, {
        id: 6,
        price: '￥15.00',
        text: '黄色',
        color: '#FBFEC5',
        imgSrc: './images/t-color/yellow.jpg'
    }],
    // diy2
    yinhuaObj: {
        default: [{
            id: '0',
            text: '取消',
            price: '￥0.00',
            imgSrc: './images/cancel.jpg'
        }, {
            id: '1',
            text: '蛋糕',
            price: '￥233.00',
            imgSrc: './images/yinhua/default/cake.png'
        }, {
            id: '2',
            text: '厨帽',
            price: '￥233.00',
            imgSrc: './images/yinhua/default/chef.png'
        }, {
            id: '3',
            text: '虫子',
            price: '￥233.00',
            imgSrc: './images/yinhua/default/croissant.png'
        }, {
            id: '4',
            text: '爱心',
            price: '￥233.00',
            imgSrc: './images/yinhua/default/favorite.png'
        }, {
            id: '5',
            text: '鱼',
            price: '￥233.00',
            imgSrc: './images/yinhua/default/fish.png'
        }, {
            id: '6',
            text: '雪糕',
            price: '￥233.00',
            imgSrc: './images/yinhua/default/ice-cream.png'
        }, {
            id: '7',
            text: '餐巾',
            price: '￥233.00',
            imgSrc: './images/yinhua/default/napkins.png'
        }, {
            id: '8',
            text: '钱包',
            price: '￥233.00',
            imgSrc: './images/yinhua/default/payment-method.png'
        }, {
            id: '9',
            text: '蛋糕2',
            price: '￥233.00',
            imgSrc: './images/yinhua/default/piece-of-cake.png'
        }, {
            id: '10',
            text: '储备',
            price: '￥233.00',
            imgSrc: './images/yinhua/default/reserved.png'
        }, {
            id: '11',
            text: '汤',
            price: '￥233.00',
            imgSrc: './images/yinhua/default/soup.png'
        }, {
            id: '12',
            text: '牛排',
            price: '￥233.00',
            imgSrc: './images/yinhua/default/steak.png'
        }, {
            id: '13',
            text: '寿司',
            price: '￥233.00',
            imgSrc: './images/yinhua/default/sushi-1.png'
        }],
        hot: [{
            id: '0',
            text: '取消',
            price: '￥0.00',
            imgSrc: './images/cancel.jpg'
        }, {
            id: '1',
            text: '热门1',
            price: '￥69.00',
            imgSrc: './images/yinhua/hot/zen-icons-doc-1.png'
        }, {
            id: '2',
            text: '热门2',
            price: '￥69.00',
            imgSrc: './images/yinhua/hot/zen-icons-key.png'
        }, {
            id: '3',
            text: '热门3',
            price: '￥69.00',
            imgSrc: './images/yinhua/hot/zen-icons-mail-full.png'
        }, {
            id: '4',
            text: '热门4',
            price: '￥69.00',
            imgSrc: './images/yinhua/hot/zen-icons-marker.png'
        }, {
            id: '5',
            text: '热门5',
            price: '￥69.00',
            imgSrc: './images/yinhua/hot/zen-icons-pencil.png'
        }],
        a: [{
            id: '0',
            text: '取消',
            price: '￥0.00',
            imgSrc: './images/cancel.jpg'
        }, {
            id: '1',
            text: '星球1',
            price: '￥66.00',
            imgSrc: './images/yinhua/a/planet_earth_venues_univearse_jupiter.png'
        }, {
            id: '2',
            text: '星球2',
            price: '￥66.00',
            imgSrc: './images/yinhua/a/planet_earth_venues_univearse_pluto.png'
        }, {
            id: '3',
            text: '星球3',
            price: '￥66.00',
            imgSrc: './images/yinhua/a/planet_earth_venues_univearse_saturn.png'
        }, {
            id: '4',
            text: '星球4',
            price: '￥66.00',
            imgSrc: './images/yinhua/a/planet_earth_venues_univearse.png'
        }, {
            id: '5',
            text: '星球5',
            price: '￥66.00',
            imgSrc: './images/yinhua/a/planet_univearse_telestial_space_mars.png'
        }, {
            id: '6',
            text: '星球6',
            price: '￥66.00',
            imgSrc: './images/yinhua/a/planet_univearse_telestial_space_pluto.png'
        }, {
            id: '7',
            text: '星球7',
            price: '￥66.00',
            imgSrc: './images/yinhua/a/planet_univearse_telestial_space.png'
        }],
        more: [{
            id: '0',
            text: '取消',
            price: '￥0.00',
            imgSrc: './images/cancel.jpg'
        }]
    },
    // diy2
    xiubiaoList: [{
        id: '0',
        text: '取消',
        price: '￥0.00',
        imgSrc: './images/cancel.jpg'
    }],
    // diy2
    yibiaoList: [{
        id: '0',
        text: '取消',
        price: '￥0.00',
        imgSrc: './images/cancel.jpg'
    }],
    // diy2
    cixiuList: [{
        id: '0',
        text: '取消',
        price: '￥0.00',
        imgSrc: './images/cancel.jpg'
    }, {
        id: '1',
        text: '刺绣1',
        price: '￥28.00',
        imgSrc: './images/cixiu/babytchi.png'
    }, {
        id: '2',
        text: '刺绣2',
        price: '￥28.00',
        imgSrc: './images/cixiu/gozarutchi.png'
    }, {
        id: '3',
        text: '刺绣3',
        price: '￥28.00',
        imgSrc: './images/cixiu/hanatchi.png'
    }, {
        id: '4',
        text: '刺绣4',
        price: '￥28.00',
        imgSrc: './images/cixiu/hashizotchi.png'
    }, {
        id: '5',
        text: '刺绣5',
        price: '￥28.00',
        imgSrc: './images/cixiu/hinotamatchi.png'
    }, {
        id: '6',
        text: '刺绣6',
        price: '￥28.00',
        imgSrc: './images/cixiu/ichigotchi.png'
    }, {
        id: '7',
        text: '刺绣7',
        price: '￥28.00',
        imgSrc: './images/cixiu/kinakomotchi.png'
    }, {
        id: '8',
        text: '刺绣8',
        price: '￥28.00',
        imgSrc: './images/cixiu/kuchipatchi.png'
    }, {
        id: '9',
        text: '刺绣9',
        price: '￥28.00',
        imgSrc: './images/cixiu/kuchipatchi1.png'
    }, {
        id: '10',
        text: '刺绣10',
        price: '￥28.00',
        imgSrc: './images/cixiu/kusatchi.png'
    }, {
        id: '11',
        text: '刺绣11',
        price: '￥28.00',
        imgSrc: './images/cixiu/mametchi.png'
    }, {
        id: '12',
        text: '刺绣12',
        price: '￥28.00',
        imgSrc: './images/cixiu/mametchi1.png'
    }, {
        id: '13',
        text: '刺绣13',
        price: '￥28.00',
        imgSrc: './images/cixiu/mametchi2.png'
    }, {
        id: '14',
        text: '刺绣14',
        price: '￥28.00',
        imgSrc: './images/cixiu/mametchi3.png'
    }, {
        id: '15',
        text: '刺绣15',
        price: '￥28.00',
        imgSrc: './images/cixiu/mametchi4.png'
    }, {
        id: '16',
        text: '刺绣16',
        price: '￥28.00',
        imgSrc: './images/cixiu/maretchi.png'
    }, {
        id: '17',
        text: '刺绣17',
        price: '￥28.00',
        imgSrc: './images/cixiu/marutchi.png'
    }, {
        id: '18',
        text: '刺绣18',
        price: '￥28.00',
        imgSrc: './images/cixiu/masktchi.png'
    }, {
        id: '19',
        text: '刺绣19',
        price: '￥28.00',
        imgSrc: './images/cixiu/memetchi.png'
    }, {
        id: '20',
        text: '刺绣20',
        price: '￥28.00',
        imgSrc: './images/cixiu/mimitchi.png'
    }]
}

Vue.component('by-header', {
    data: function() {
        return {

        }
    },
    ready: function() {

    },
    template: ('<div class="header"><img src="./images/menus.png" alt=""> BY !</div>')
});


window.getUrlParam = function(param) {
    var reg = new RegExp("(^|&)" + param + "=([^&]*)(&|$)");
    var r = window.location.search.substr(1).match(reg);
    if (r != null) {
        return unescape(r[2]);
    }
    return null;
};
